syntax = "proto2";

import "steammessages_base.proto";
import "webuimessages_base.proto";

option cc_generic_services = true;
option optimize_for = SPEED;

service TransportAuth {
    rpc Authenticate(CTransportAuth_Authenticate_Request) returns (CTransportAuth_Authenticate_Response);
    rpc NotifyStartShutdown(CTransportAuth_StartShutdown_Notification) returns (WebUINoResponse);
}

message CTransportAuth_Authenticate_Request {
    optional string auth_key = 1;
}

message CTransportAuth_Authenticate_Response {
    
}

message CTransportAuth_StartShutdown_Notification {
    
}
